"""empty message

Revision ID: bd1142d6a6da
Revises: f23da7a88b0f
Create Date: 2024-04-06 21:52:09.690972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1142d6a6da'
down_revision: Union[str, None] = 'f23da7a88b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chats',
        'uuid',
        new_column_name='session_id'
    )
    op.alter_column(
        'contents',
        'link',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'contents',
        'link',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True
    )
    op.alter_column(
        'chats',
        'session_id',
        new_column_name='uuid'
    )
    # ### end Alembic commands ###
