"""empty message

Revision ID: f23da7a88b0f
Revises: 730d79727450
Create Date: 2023-12-28 19:57:02.304653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f23da7a88b0f'
down_revision: Union[str, None] = '730d79727450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('contents', sa.Column('dataset', sa.String()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'dataset')
    # ### end Alembic commands ###
