version: '3.3'
services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: talkdai
      POSTGRES_PASSWORD: talkdai
      POSTGRES_DB: talkdai
    volumes:
       - ./data/db:/var/lib/postgresql/data
       - ./psql/db-ext-vector.sql:/docker-entrypoint-initdb.d/db-ext-vector.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "talkdai", "-U", "talkdai"]
      interval: 10s
      timeout: 5s
      retries: 5
  dialog:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - ./data/:/app/data/
      - ./.empty:/app/data/db
      - ./static:/app/static
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://talkdai:talkdai@db:5432/talkdai
      - STATIC_FILE_LOCATION=/app/static
      - PGPASSWORD=talkdai
    env_file:
      - .env
