version: '3.3'
services:
  db:
    image: ankane/pgvector:v0.5.0
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: talkdai
      POSTGRES_PASSWORD: talkdai
      POSTGRES_DB: talkdai
    volumes:
       - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "talkdai", "-U", "talkdai"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./data:/data
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    volumes:
      - ./front:/front
    ports:
      - '8080:8080'
    depends_on:
      - web
    env_file:
      - .env